const products = [{
        id: 1,
        showCaseImgs: [
            "1.jpg",
            "2.jpg",
            "3.jpg",
            "4.jpg",
            "5.jpg",
            "6.jpg",
            "7.jpeg",
            "8.jpeg",
        ],
        video: 'src="https://www.youtube.com/embed/FsnFPPbaNMM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen',
        productName: 'MSI GE66 DragonShield 10SF 483VN',
        brand: 'MSI',
        rate: 4.9,
        reviews: 75,
        sold: 129,
        screen: '15.6" FHD (1920 x 1080)',
        processor: 'Intel® Core™ i7-10875H 2.30GHz - 5.10GHz 8 Cores 12 Threads',
        memory: '16GB (8GB x2) DDR4 3200MHz',
        hardDrive: '1 TB NVMe PCIe Gen3x4',
        oldPrice: '$2,700',
        newPrice: '$2,600',
        gpu: 'NVIDIA GeForce GTX 1650 4GB GDDR6 + Intel UHD Graphics',
        connection: 'Killer ax Wi-Fi + Bluetooth v5.1',
        keyBoard: 'RGB Steelseries',
        weight: '2.38Kg',
        battery: 'Li-Ion 4-Cell 99.9Wh'
    },
    {
        id: 2,
        showCaseImgs: [
            "1.png",
            "2.jpg",
            "3.jpg",
            "4.jpg",
            "5.png",
            "8.jpg",
            "10.jpg",
            "11.jpg",
        ],
        video: 'src="https://www.youtube.com/embed/eRNuyFyfRRY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen',
        productName: 'MSI 15.6" Creator Series Creator 15 Multi-Touch',
        brand: 'MSI',
        rate: 4.7,
        reviews: 71,
        sold: 92,
        screen: 'LCD 15.6" FHD (1920 x 1080) TouchScreen',
        processor: 'Intel Core i7-10875H 2.3GHz-5.1GHz 8-Core',
        memory: '16GB (8GB x2) DDR4 2666MH (maximum 64GB)',
        hardDrive: '512 GB M.2 NVMe PCIe',
        oldPrice: '$1,599',
        newPrice: '$1,399',
        aboutProduct: "The machine is also equipped with a 2TB M.2 PCIe SSD for fast read and write speeds, opening applications in a snap to enhance your experience. If you need to upgrade the machine, the machine has up to 2 M.2 SSD slots to support you to expand the hard drive when needed.Nvidia Geforce RTX 3080 Ti GDDR6 VGA for extremely smooth graphics processing, you can operate smoothly on professional graphics software such as Photoshop, Ai or 3DMAX, Vlog editing, video editing is not too complicated complex. Games that require high graphics such as Assassin's Creed Valhalla, Doom Eternal, Borderlands 3, ... also do not make this machine difficult.",
        gpu: 'NVIDIA GeForce RTX 2060 with 6 GB GDDR6 VRAM',
        connection: 'Wi-Fi 6 (802.11ax) + Bluetooth 5.1',
        keyBoard: '84-Key Notebook Backlight',
        weight: '2.1Kg',
        battery: 'Li-Ion 4-Cell 99.9 Wh'
    },
    {
        id: 3,
        showCaseImgs: [
            "1.png",
            "2.jpg",
            "3.jpg",
            "4.png",
            "5.png",
            "10.jpg",
            "8.jpg",
            "9.jpg",
        ],
        video: 'src="https://www.youtube.com/embed/_9JgeOhm-9k" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen',
        productName: 'MSI GL75 Leopard',
        brand: 'MSI',
        rate: 4.5,
        reviews: 23,
        sold: 61,
        screen: 'IPS 15.6" FHD (1920 x 1080)',
        processor: 'Intel Core i7-10750H 2.6GHz-5.0GHz 6-Core',
        memory: '16GB (8GB x2) DDR4 2666MH (maximum 64GB)',
        hardDrive: '512 GB M.2 NVMe PCIe',
        oldPrice: '$1,599',
        newPrice: '$1,399',
        aboutProduct: "Owning a 17.3-inch screen with UHD 4K resolution, the MSI GE76 12UHS 480VN gaming laptop is sharp in every detail, IPS panel for wide viewing angles combined with a scan frequency of up to 120Hz to help you capture Battle situation of the game quickly and accurately, thereby giving reasonable manipulations to improve the possibility of victory. With this MSI laptop, the visual experience of games is smooth and responsive when playing fast-paced games like racing, so as not to miss a second.",
        gpu: 'NVIDIA GeForce GTX 1660 Ti with 6 GB GDDR6 VRAM',
        connection: 'Wi-Fi 6 (802.11ax) + Bluetooth 5.1',
        keyBoard: 'Notebook Keyboard with Backlight, Number Pad',
        weight: '2.3Kg',
        battery: 'Lithium-Ion 6-Cell: 51 Wh'
    },
    {
        id: 4,
        showCaseImgs: [
            "1.png",
            "2.jpg",
            "3.jpg",
            "4.png",
            "5.jpg",
            "6.jpg",
            "7.jpg",
            "8.jpg"
        ],
        video: 'src="https://www.youtube.com/embed/h8vNlfMDXNs" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen',
        productName: 'ASUS TUF A15',
        brand: 'ASUS',
        rate: 4.6,
        reviews: 37,
        sold: 55,
        screen: 'IPS 15.6" FHD (1920 x 1080)',
        processor: 'AMD Ryzen 7 4800H 2.9GHz-4.2GHz 8-Core',
        memory: '16GB (8GB x2) DDR4 3200MHz (maximum 32GB)',
        hardDrive: '512 GB M.2 NVMe PCIe',
        oldPrice: '$1,599',
        newPrice: '$1,399',
        aboutProduct: "One of the warriors from the ASUS family that is made up of the most advanced components, the most superior to the present time is the Asus ROG Zephyrus M16 GU603ZX K8025W gaming laptop. This product has a sophisticated design and is not too aggressive compared to other gaming laptops, along with excellent speed processing, many great features, compacted into just a weight of 1.9kg. so you can take it anywhere and see it as a weapon to bomb all your battlefields.",
        gpu: 'NVIDIA GeForce GTX 1650 Ti with 4 GB GDDR6 VRAM',
        connection: 'Wi-Fi 6 (802.11ax) + Bluetooth 5.1',
        keyBoard: 'Notebook Keyboard with Backlight',
        weight: '2.3Kg',
        battery: 'Lithium-Ion 3-Cell: 48 Wh'
    },
    {
        id: 5,
        showCaseImgs: [
            "1.png",
            "2.jpg",
            "3.png",
            "4.jpg",
            "5.png",
            "6.jpg",
            "7.jpg",
            "8.jpg"
        ],
        video: 'src="https://www.youtube.com/embed/v7WiLjjTafI&t" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen',
        productName: 'Acer Nitro 5',
        brand: 'Acer',
        rate: 4.7,
        reviews: 43,
        sold: 64,
        screen: 'IPS-Type LCD 15.6" FHD (1920 x 1080)',
        processor: 'Intel Core i5-9300H 2.4GHz - 4.1GHz Quad-Core',
        memory: '8GB DDR4 3200MHz (maximum 32GB)',
        hardDrive: '512 GB M.2 NVMe PCIe',
        oldPrice: '$800',
        newPrice: '$696',
        aboutProduct: "Surrounding the Acer Nitro 5 gaming laptop is a high-grade magnesium aluminum material that is extremely durable and long-lasting. Limiting scratches and bumps, that helps you feel more secure about protecting your laptop carefully. The A-face is uniquely designed from 8,279 CNC-cut dots with a layer of reflective Prismatic Film that adds uniqueness in every little detail, highlighting the unique qualities of gamers combined with a bold mysterious black color. gaming.",
        gpu: 'NVIDIA GeForce GTX 1650 with 4 GB GDDR5 VRAM',
        connection: 'Wi-Fi 6 (802.11ax) + Bluetooth 5.1',
        keyBoard: 'Notebook Keyboard with Backlight, Number Pad',
        weight: '2.5Kg',
        battery: 'Lithium-Ion 4-Cell: 55 Wh'
    },
    {
        id: 6,
        showCaseImgs: [
            "1.jpg",
            "2.jpg",
            "3.jpg",
            "4.jpg",
            "5.jpg",
            "3.jpg",
            "6.jpg",
            "7.jpg"
        ],
        video: 'src="https://www.youtube.com/embed/D6alZqo2Dfc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen',
        productName: 'MSI GE Series GE66 Raider Gaming Laptop',
        brand: 'MSI',
        rate: 4.5,
        reviews: 21,
        sold: 43,
        screen: 'LCD 15.6" FHD (1920 x 1080)',
        processor: ' Intel Core i7-10870H 2.2GHz - 5.0GHz 8-Core',
        memory: '32GB (16GBx2) DDR4 3200MHz',
        hardDrive: '1TB M.2 NVMe PCIe',
        oldPrice: '$2,399',
        newPrice: '$2,199',
        aboutProduct: "MSI GE Series GE66 Raider Gaming Laptop has an ultra-thin screen with a display ratio of up to 94%, almost giving users a visual experience that is extremely vivid and much larger than usual, screen panels with frequency 165Hz/3ms at WQXGA resolution with 100% DCI-P3 wide color gamut, impressively smooth transitions. ",
        gpu: 'NVIDIA GeForce RTX 3080 with 16 GB GDDR6 VRAM',
        connection: 'Wi-Fi 6 (802.11ax) + Bluetooth 5.1',
        keyBoard: 'Notebook Keyboard with Backlight',
        weight: '2.3Kg',
        battery: 'Lithium-Ion 4-Cell 99 Wh'
    },
    {
        id: 7,
        showCaseImgs: [
            "1.png",
            "2.jpg",
            "3.jpg",
            "4.png",
            "5.png",
            "2.jpg",
            "6.jpg",
            "7.png"
        ],
        video: 'src="https://www.youtube.com/embed/wndadfxBdpA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen',
        productName: 'Razer Blade Gaming Laptop',
        brand: 'Razer',
        rate: 4.6,
        reviews: 14,
        sold: 22,
        screen: 'LCD 15.6" FHD (1920 x 1080)',
        processor: 'Intel Core i7-10750H 6-Core 2.6GHz - 5.0GHz',
        memory: '16GB (8GBx2) DDR4 2933MHz',
        hardDrive: '512GB M.2 NVMe PCIe',
        oldPrice: '$1,799',
        newPrice: '$1,699',
        aboutProduct: "The ErgoLift hinge with a maximum 180-degree opening allows you to share the content on the screen with everyone around to make connecting and supporting each other easier, closer and more professional.",
        gpu: 'NVIDIA GeForce RTX 3060 with 6 GB GDDR6 VRAM',
        connection: 'Wi-Fi 6 (802.11ax) + Bluetooth 5.1',
        keyBoard: 'Notebook Keyboard with Backlight',
        weight: '2Kg',
        battery: 'Lithium-Ion 4-Cell 65 Wh'
    },
    {
        id: 8,
        showCaseImgs: [
            "1.jpg",
            "2.jpg",
            "3.jpg",
            "4.jpg",
            "5.png",
            "1.jpg",
            "2.jpg",
            "3.jpg"
        ],
        video: 'src="https://www.youtube.com/embed/z8DnwS45YCk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen',
        productName: 'Acer Predator Helios 300 Gaming Laptop',
        brand: 'Acer',
        rate: 4.8,
        reviews: 17,
        sold: 31,
        screen: 'IPS 15.6" FHD (1920 x 1080)',
        processor: 'Intel Core i7-10750H 6-Core 2.6GHz - 5.0GHz',
        memory: '16GB (8GBx2) DDR4 2933MHz',
        hardDrive: '1TB M.2 NVMe PCIe',
        oldPrice: '$1,399',
        newPrice: '$1,199',
        aboutProduct: "Acer Predator Helios 300 Gaming Laptop is equipped with Dolby Atmos surround speakers with 6 satellite speakers and an impressive subwoofer. Deliver a realistic sound quality experience like being in the cinema or great in intense games. Noise cancellation with advanced AI technology will help eliminate background noises for clear and clear sound quality.",
        gpu: 'NVIDIA GeForce RTX 3060 with 6 GB GDDR6 VRAM',
        connection: 'Wi-Fi 6 (802.11ax) + Bluetooth 5.1',
        keyBoard: 'Notebook Keyboard with Backlight',
        weight: '2.5Kg',
        battery: 'Lithium-Ion 4-Cell 65 Wh'
    },
    {
        id: 9,
        showCaseImgs: [
            "1.png",
            "2.png",
            "3.png",
            "4.png",
            "5.png",
            "3.png",
            "1.png",
            "3.png"
        ],
        video: 'src="https://www.youtube.com/embed/oyVtHl0zk58" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen',
        productName: 'ASUS Republic of Gamers Strix G17 Gaming Laptop',
        brand: 'ASUS',
        rate: 4.9,
        reviews: 51,
        sold: 72,
        screen: 'IPS-Type LCD 17.3" FHD (1920 x 1080)',
        processor: 'AMD Ryzen 9 5900HX 3.3GHz - 4.6GHz 8-Core',
        memory: '32GB (16GBx2) DDR4 3200MHz',
        hardDrive: '1TB M.2 NVMe PCIe',
        oldPrice: '$ 1,799',
        newPrice: '$ 1,599',
        aboutProduct: "To be able to fight heavy games, Asus has equipped ROG Zephyrus M16 with an advanced Intel Core i9-11900H processor combined with 32GB DDR4-3200Mhz SO-DIMM to provide a multi-tasking ability. , especially heavy-duty tasks will be easier than ever. ",
        gpu: 'NVIDIA GeForce RTX 3070 with 8 GB GDDR6 VRAM',
        connection: 'Wi-Fi 6 (802.11ax) + Bluetooth 5.1',
        keyBoard: 'Chiclet Notebook Keyboard with Backlight',
        weight: '2.7Kg',
        battery: 'Lithium-Ion 4-Cell 90 Wh'
    },
    {
        id: 10,
        showCaseImgs: [
            "1.jpg",
            "2.png",
            "3.jpg",
            "4.jpg",
            "5.png",
            "6.jpg",
            "7.jpg",
            "9.png"
        ],
        video: 'src="https://www.youtube.com/embed/wVV34dfJOl8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen',
        productName: 'MSI GF65 Thin 10UE-046 Gaming Laptop',
        brand: 'MSI',
        rate: 4.7,
        reviews: 31,
        sold: 46,
        screen: 'IPS-Type LCD 15.6" FHD (1920 x 1080)',
        processor: 'Intel Core i7-10750H 6-Core 2.6GHz - 5GHz',
        memory: '16GB (8GBx2) DDR4 3200MHz',
        hardDrive: '1TB M.2 NVMe PCIe',
        oldPrice: '$ 1,599',
        newPrice: '$ 1,399',
        aboutProduct: "Together with SSD up to 2TB M.2 NVMe™ like a giant warehouse to help you fully store all important data, limit slowness and speed data processing speed. Besides, there is also the high-end NVIDIA® GeForce RTX™ 3080Ti 8GB GDDR6 graphics card not only for smoother gameplay, but also for professional photo editing, video editing, and Photoshop and Lightroom applications. , Ai,...",
        gpu: 'NVIDIA GeForce RTX 3060 with 6 GB GDDR6 VRAM',
        connection: 'Wi-Fi 6 (802.11ax) + Bluetooth 5.1',
        keyBoard: 'Notebook Keyboard with Backlight',
        weight: '1.9Kg',
        battery: 'Lithium-Ion 3-Cell 51 Wh'
    },
    {
        id: 11,
        showCaseImgs: [
            "1.jpg",
            "2.jpg",
            "3.jpg",
            "4.png",
            "5.png",
            "7.jpg",
            "8.jpg",
            "9.jpg"
        ],
        video: 'src="https://www.youtube.com/embed/XHk-mOOibuI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen',
        productName: 'MSI GS66 Stealth Gaming Laptop (Core Black)',
        brand: 'MSI',
        rate: 4.8,
        reviews: 22,
        sold: 37,
        screen: 'LCD 15.6" FHD (1920 x 1080)',
        processor: 'Intel Core i7-10870H 8-Core 2.2GHz - 5GHz',
        memory: '32GB (16GBx2) DDR4 3200MHz',
        hardDrive: '1TB M.2 NVMe PCIe',
        oldPrice: '$ 2,500',
        newPrice: '$ 2,399',
        aboutProduct: "The keyboard of the MSI GS66 Stealth Gaming Laptop series often gives extremely high bounce, MSI GS66 Stealth Gaming Laptop is no exception. Daily typing is also no longer worried about hand fatigue, causing discomfort because the product feels extremely smooth and fast. Combined with the Backlit RGB LED system equipped for the keyboard , increasing the light ability for you to see clearly when working or playing games at night. ",
        gpu: 'NVIDIA GeForce RTX 3070 Max-Q with 8 GB GDDR6 VRAM',
        connection: 'Wi-Fi 6 (802.11ax) + Bluetooth 5.1',
        keyBoard: 'Notebook Keyboard with Backlight',
        weight: '2.1Kg',
        battery: 'Lithium-Ion Polymer (LiPo) 4-Cell 100 Wh'
    },
    {
        id: 12,
        showCaseImgs: [
            "1.jpg",
            "2.jpg",
            "3.jpg",
            "4.jpg",
            "5.jpg",
            "1.jpg",
            "2.jpg",
            "3.jpg"
        ],
        video: 'src="https://www.youtube.com/embed/eNw-C_4m_Ho" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen',
        productName: 'ASUS RoG Zephyrus G15 GA502IU Gaming Laptop',
        brand: 'ASUS',
        rate: 4.8,
        reviews: 43,
        sold: 44,
        screen: 'IPS-Type LCD 15.6" FHD (1920 x 1080)',
        processor: 'AMD Ryzen 7 4800HS 2.9GHz - 4.2GHz 8-Core',
        memory: '16GB (8GBx2) DDR4 3200MHz',
        hardDrive: '1TB M.2 NVMe PCIe',
        oldPrice: '$ 1,100',
        newPrice: '$ 1,269',
        aboutProduct: "Belonging to the high-end gaming laptop line , it will definitely come with an impressive battery capacity.",
        gpu: 'NVIDIA GeForce GTX 1660 Ti Max-Q with 6 GB GDDR6 VRAM',
        connection: 'Wi-Fi 6 (802.11ax) + Bluetooth 5.1',
        keyBoard: 'Chiclet Notebook Keyboard with Backlight',
        weight: '2.1Kg',
        battery: 'Lithium-Ion 4-Cell 76 Wh'
    },
    {
        id: 13,
        showCaseImgs: [
            "1.png",
            "2.png",
            "3.png",
            "4.png",
            "5.png",
            "2.png",
            "5.png",
            "a.png",
        ],
        video: 'src="https://www.youtube.com/embed/tkmUReooM4k" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen',
        productName: 'MSI 14" Prestige 14 Laptop (Rose Pink)',
        brand: 'MSI',
        rate: 4.8,
        reviews: 70,
        sold: 120,
        screen: '14" 1920 x 1080 IPS Display',
        processor: 'Intel Core i7 4-Core (11th Gen) 1.2GHz',
        memory: '16GB (8GB x2) DDR4 3200MHz',
        hardDrive: '1TB M.2 SSD',
        oldPrice: '$1,549',
        newPrice: '$1,400',
        aboutProduct: "has equipped a standard 4-Cell Li-ion battery with a capacity of 90Whrs with a capacity of 90Whrs along with a 100W PD fast charging adapter that provides excellent battery life compared to other laptops, can watch videos continuously. for 9 10 hours. Meet all the needs of daily use without having to worry about charging problems.",
        gpu: 'NVIDIA GTX 1650 Max-Q',
        connection: 'Bluetooth 5.1 and Wi-Fi 6',
        keyBoard: 'Backlight',
        weight: '2.5Kg',
        battery: 'Li-Ion 4-Cell 99.9Wh'
    },
    {
        id: 14,
        showCaseImgs: [
            "1.png",
            "2.png",
            "3.png",
            "4.png",
            "5.png",
            "2.png",
            "4.png",
            "a.png",
        ],
        video: 'src="https://www.youtube.com/embed/wyCkN24gThM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen',
        productName: 'MSI 17.3" WS75 Series Mobile Workstation',
        brand: 'MSI',
        rate: 4.5,
        reviews: 56,
        sold: 90,
        screen: '17.3" 1920 x 1080 Full HD IPS Display',
        processor: '2.4 GHz Intel Core i9- 10980HK Eight - Core',
        memory: '64GB DDR4 RAM',
        hardDrive: '1TB NVMe PCIe M.2 SSD',
        oldPrice: '$3,549',
        newPrice: '$3,400',
        aboutProduct: "are equipped with a variety of ports along the sides of the body. In addition to the USB port, memory card reader, charging port, .. ",
        gpu: 'NVIDIA Quadro RTX 5000(16GB GDDR6)',
        connection: 'Wi - Fi 6(802.11ax) | Bluetooth 5.1',
        keyBoard: 'Backlight',
        weight: '2.7Kg',
        battery: 'Li-Ion 4-Cell 99.9Wh'
    },
    {
        id: 15,
        showCaseImgs: [
            "1.png",
            "2.png",
            "3.png",
            "4.png",
            "5.png",
            "3.png",
            "6.png",
            "a.png",
        ],
        video: 'src="https://www.youtube.com/embed/gr6cfvyfI0s" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen',
        productName: 'MSI 15.6" Prestige 15 Laptop (Urban Silver)',
        brand: 'MSI',
        rate: 4.4,
        reviews: 72,
        sold: 35,
        screen: '15.6" 3840 x 2160 Display',
        processor: '1.2 GHz Intel Core i7 4-Core (11th Gen)',
        memory: '32GB of DDR4',
        hardDrive: '1TB M.2 SSD',
        oldPrice: '$1,799',
        newPrice: '$1,700',
        aboutProduct: "is also equipped with 1 Thunderbolt™ 4 port that supports DisplayPort™ and Power Delivery fast charging technology to help you comfortably experience heavy games without having to Worry about battery drain issue.",
        gpu: 'NVIDIA GeForce GTX 1650 Max - Q',
        connection: 'Bluetooth 5.1 and Wi- Fi 6',
        keyBoard: 'Backlit Keyboard',
        weight: '2.3Kg',
        battery: 'Li-Ion 4-Cell 99.9Wh'

    },
    {
        id: 16,
        showCaseImgs: [
            "1.png",
            "2.png",
            "3.png",
            "4.png",
            "5.png",
            "7.png",
            "8.png",
            "a.png",
        ],
        video: 'src="https://www.youtube.com/embed/h63-g61V568" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen',
        productName: 'MSI 15.6" GE63 Raider RGB Gaming Laptop',
        brand: 'MSI',
        rate: 5.0,
        reviews: 140,
        sold: 95,
        screen: '15.6" 1920 x 1080 144 Hz IPS Display',
        processor: '2.6 GHz Intel Core i7- 9750H Six - Core',
        memory: '32GB DDR4',
        hardDrive: ' 512GB NVMe SSD + 1TB HDD',
        oldPrice: '$1,399',
        newPrice: '$1,300',
        aboutProduct: "Improve the connection with other peripheral devices more easily such as mouse , keyboard, projector , speaker, .... support for work as well as play games more fully.",
        gpu: 'NVIDIA GeForce RTX 2060(6GB GDDR6)',
        connection: 'Bluetooth 5.1 and Wi - Fi 5(802.11ac) ',
        keyBoard: ' MSI Mystic Light RGB Lighting',
        weight: '2.8Kg',
        battery: 'Li-Ion 4-Cell 99.9Wh'
    },
    {
        id: 17,
        showCaseImgs: [
            "1.png",
            "2.png",
            "3.png",
            "4.png",
            "5.png",
            "2.png",
            "3.png",
            "a.png"
        ],
        video: 'src="https://www.youtube.com/embed/QkajSRqOyxs" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen',
        productName: 'MSI 14" Prestige 14 EVO Laptop',
        brand: 'MSI',
        rate: 4.0,
        reviews: 45,
        sold: 72,
        screen: '14" FHD 1920 x 1080 IPS Display',
        processor: '1.2 GHz Intel Core i7 Quad- Core 11th Gen',
        memory: '16 GB LPDDR4X',
        hardDrive: '512GB NVMe SSD',
        oldPrice: '$1,149',
        newPrice: '$1,049',
        aboutProduct: "In addition to the features that this ROG Zephyrus M16 brings, it also has a dedicated heat dissipation system and effective cooling through the chassis. Constructed from Liquid Metal, this is a form of liquid metal compound used to cool the CPU. ",
        gpu: 'NVIDIA GeForce GTX 1650 Max-Q',
        connection: 'Wi - Fi 6(802.11ax) | Bluetooth 5.1',
        keyBoard: 'Thunderbolt 4 | USB Type-A',
        weight: '2.6Kg',
        battery: 'Li-Ion 4-Cell 99.9Wh'

    },
    {
        id: 18,
        showCaseImgs: [
            "1.png",
            "2.png",
            "3.png",
            "4.png",
            "5.png",
            "1.png",
            "6.png",
            "c.png",
        ],
        video: 'src="https://www.youtube.com/embed/3sa-ZqveD9E" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen',
        productName: 'MSI 13.4 "Summit E13FlipEvo (Ink Black)',
        brand: 'MSI',
        rate: 4.2,
        reviews: 40,
        sold: 72,
        screen: '13, 4 "FHD 1920 x 1200',
        processor: '1, 2 GHz Intel Core i7 Quad- Core 11th Gen',
        memory: ' 16 GB LPDDR4X',
        hardDrive: ' 512GB  SSD M.2',
        oldPrice: '$1,549',
        newPrice: '$1,449',
        aboutProduct: " In other words, this is a custom self-cleaning 2.0 thermal module that removes dust for improved long-term stability.",
        gpu: 'NVIDIA GeForce GTX 1650 Max-Q',
        connection: 'Wi - Fi 6(802.11ax) | Bluetooth 5.2',
        keyBoard: 'Thunderbolt 4 | USB Type-C',
        weight: '2.8Kg',
        battery: 'Li-Ion 4-Cell 99.9Wh'
    },
    {
        id: 19,
        showCaseImgs: [
            "1.png",
            "2.png",
            "3.png",
            "4.png",
            "5.png",
            "2.png",
            "3.png",
            "a.png",
        ],
        video: 'src="https://www.youtube.com/embed/UysOcg6gITo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen',
        productName: 'MSI 14" Modern 14B Notebook (Beige Mousse)',
        brand: 'MSI',
        rate: 4.8,
        reviews: 49,
        sold: 90,
        screen: '14" 1920 x 1080 FHD IPS Display',
        processor: '3.0 GHz Intel Core i3 2-Core(11th Gen)',
        memory: '8GB of DDR4 RAM ',
        hardDrive: ' 512GB  SSD ',
        oldPrice: '$649',
        newPrice: '$549',
        aboutProduct: "The Arc Flow fan is designed to produce impressive airflow with reduced turbulence, ensuring powerful yet quiet cooling.",
        gpu: 'Intel Iris Xe Graphics',
        connection: 'Wi - Fi 6(802.11ax) | Bluetooth 5.2',
        keyBoard: 'Thunderbolt 4 | USB Type-C',
        weight: '2.2Kg',
        battery: 'Li-Ion 4-Cell 99.9Wh'
    },
    {
        id: 20,
        showCaseImgs: [
            "1.png",
            "2.png",
            "3.png",
            "4.png",
            "5.png",
            "1.png",
            "3.png",
            "c.png",
        ],
        video: 'src="https://www.youtube.com/embed/HG_nG6wGhlM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen',
        productName: 'MSI 15 Modern 15 Notebook',
        brand: 'MSI',
        rate: 4.8,
        reviews: 49,
        sold: 90,
        screen: '14" 1920 x 1080 FHD IPS Display',
        processor: '3.0 GHz Intel Core i3 2-Core(11th Gen)',
        memory: '8GB of DDR4 RAM ',
        hardDrive: ' 512GB  SSD ',
        oldPrice: '$649',
        newPrice: '$549',
        aboutProduct: "is equipped with all-new 4800Mhz DDR5 RAM, up to 50% performance with older generation DDR4. This super-fast RAM makes all activities of Laptop Gaming very smooth, from intense gaming, editing, 3D rendering to web surfing and entertainment.",
        gpu: 'Intel Iris Xe Graphics',
        connection: 'Wi - Fi 6(802.11ax) | Bluetooth 5.2',
        keyBoard: 'Thunderbolt 4 | USB Type-C',
        weight: '2.2Kg',
        battery: 'Li-Ion 4-Cell 99.9Wh'
    },
    {
        id: 21,
        showCaseImgs: [
            "1.png",
            "2.png",
            "3.png",
            "4.png",
            "5.png",
            "4.png",
            "8.png",
            "a.png",
        ],
        video: 'src="https://www.youtube.com/embed/vAG47dRNTRg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen',
        productName: 'MSI 15.6" Summit B15 Laptop',
        brand: 'MSI',
        rate: 4.8,
        reviews: 79,
        sold: 49,
        screen: '14" 1920 x 1080 FHD IPS Display',
        processor: '1.6 GHz Intel Core i5- 10210U Quad - Core',
        memory: '8GB of DDR4 RAM ',
        hardDrive: ' 512GB  SSD ',
        oldPrice: '$990',
        newPrice: '$890',
        aboutProduct: "Confidently conquer the toughest challenges with a 4th Gen PCIe SSD. With bandwidth up to 7000MB/s, massive files and blockbuster games will be loaded in the blink of an eye.",
        gpu: 'NVIDIA GeForce GTX 1650 Max - Q',
        connection: 'Wi - Fi 6(802.11ax) | Bluetooth 5.2',
        keyBoard: 'Backlit Keyboard',
        weight: '2.5Kg',
        battery: 'Li-Ion 4-Cell 99.9Wh'
    },
    {
        id: 22,
        showCaseImgs: [
            "1.png",
            "2.png",
            "3.png",
            "4.png",
            "5.png",
            "1.png",
            "3.png",
            "a.png",
        ],
        video: 'src="https://www.youtube.com/embed/Z1HBNi0LTco" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen',
        productName: 'MSI 14" Prestige 14 Laptop',
        brand: 'MSI',
        rate: 4.7,
        reviews: 20,
        sold: 12,
        screen: '14" 1920 x 1080 Full HD IPS Display',
        processor: '1.6 GHz Intel Core i5- 10210U Quad - Core',
        memory: ' 16 GB LPDDR4X',
        hardDrive: ' 512GB NVMe SSD',
        oldPrice: '$1,179',
        newPrice: '$1,079',
        aboutProduct: "NVIDIA DLSS enhances performance dramatically without sacrificing quality by using advanced AI technology. Ray tracing technology delivers the most realistic images at high speed thanks to the 2nd Gen RT Core.",
        gpu: 'NVIDIA GeForce GTX 1650 Max-Q (4GB GDDR5)',
        connection: 'Wi - Fi 6(802.11ax) | Bluetooth 5.0',
        keyBoard: 'USB Type-A & Type-C | Thunderbolt 3',
        weight: '2.8Kg',
        battery: 'Li-Ion 4-Cell 99.9Wh'
    },
    {
        id: 23,
        showCaseImgs: [
            "1.png",
            "2.png",
            "3.png",
            "4.png",
            "5.png",
            "1.png",
            "4.png",
            "6.png",
        ],
        video: 'src="https://www.youtube.com/embed/6qouxrgDEpU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen',
        productName: 'MSI 15.6" Creator Series Modern 15 Laptop',
        brand: 'MSI',
        rate: 4.6,
        reviews: 29,
        sold: 39,
        screen: '15.6" 1920 x 1080 Full HD IPS Display',
        processor: '1.8 GHz Intel Core i7- 10510U Quad - Core',
        memory: ' 8GB DDR4 ',
        hardDrive: ' 512GB NVMe PCIe M.2 SSD',
        oldPrice: '$889',
        newPrice: '$870',
        aboutProduct: "Really quiet heat dissipation when performing light tasks with 0dB technology. In Silent mode, the cooling system will turn off all fans when handling daily tasks to conduct passive air dissipation. This helps you focus on your work and enjoy great movies without distractions. If the GPU or CPU temperature rises above 60°C, the fan will automatically turn back on.",
        gpu: 'NVIDIA GeForce MX330 (2GB GDDR5)',
        connection: 'Wi - Fi 5(802.11ac) | Bluetooth 5.0',
        keyBoard: 'USB Type-A & Type-C | HDMI',
        weight: '2.5Kg',
        battery: 'Li-Ion 4-Cell 99.9Wh'
    },
    {
        id: 24,
        showCaseImgs: [
            "1.png",
            "2.png",
            "3.png",
            "7.png",
            "5.png",
            "4.png",
            "5.png",
            "6.png",
        ],
        video: 'src="https://www.youtube.com/embed/QeVlcnZew8E" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen',
        productName: 'MSI 15.6" Prestige 15 Laptop',
        brand: 'MSI',
        rate: 4.3,
        reviews: 46,
        sold: 30,
        screen: '15.6" 3840 x 2160 4K Display',
        processor: '1.1 GHz Intel Core i7- 10710U Six - Core',
        memory: ' 32GB DDR4 ',
        hardDrive: '1TB NVMe PCIe SSD',
        oldPrice: '$1,889',
        newPrice: '$1,770',
        aboutProduct: "Heat is distributed through four heatsinks, each designed with copper fins as thin as 0.1mm. These fins are half the size of the regular size, with a thicker density allowing for increased surface area, more efficient heat dissipation, and reduced air resistance. Up to 218 heatsink fins form a total area of ​​up to 107,131mm².",
        gpu: 'NVIDIA GeForce GTX 1650 (4GB GDDR5)',
        connection: 'Wi - Fi 6(802.11ax) | Bluetooth 5.0',
        keyBoard: 'Backlight',
        weight: '2.3Kg',
        battery: 'Li-Ion 4-Cell 99.9Wh'
    },

    {
        id: 25,
        showCaseImgs: [
            "1.png",
            "2.png",
            "3.png",
            "4.png",
            "5.png",
        ],
        video: 'src="https://www.youtube.com/embed/VzrR9-upMCA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen',
        productName: 'MSI Raider GE76 12UHS 480VN',
        brand: 'MSI',
        rate: 5.0,
        reviews: 46,
        sold: 100,
        screen: '17.3" UHD (3840 x 2160) IPS, 120Hz, 100% sRGB, 100% Adobe RGB, NanoEdge',
        processor: 'Intel Core i9-12900HK 3.8GHz up to 5.0GHz 24MB',
        memory: ' 64GB DDR4 ',
        hardDrive: '2TB NVMe PCIe SSD',
        oldPrice: '$5,199',
        newPrice: '$4,787',
        aboutProduct: "Our upgraded heatsink module design includes shorter dust-proof ducts, leaving up to 5% more space around the fan, which improves air circulation by up to 15%. Preventing dust accumulation helps to ensure long-term stable and reliable system operation.",
        gpu: 'NVIDIA GeForce RTX 3080Ti 16GB GDDR6 Up to 1690MHz Boost Clock, 175W Maximum Graphics Power with Dynamic Boost. Max. 220W CPU-GPU Power with MSI OverBoost Technology',
        connection: 'Wi - Fi 6(802.11ax) | Bluetooth 5.0',
        keyBoard: 'Per key RGB steelseries KB',
        weight: '2.9Kg',
        battery: '4 cells, 99.9Whr'
    },
    {
        id: 26,
        showCaseImgs: [
            "1.png",
            "2.png",
            "3.png",
            "4.png",
            "5.png",
            "6.png",
            "7.png",
            "8.png",
        ],
        video: 'src="https://www.youtube.com/embed/_Wz-SdIQ4_g" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen',
        productName: 'Acer Predator Triton 500 SE',
        brand: 'ACER',
        rate: 4.9,
        reviews: 46,
        sold: 100,
        screen: '16-inch WQXGA (2560 x 1600) 16:10, IPS-level, anti-glare display, 100%, 165Hz, 3ms, 500 nits',
        processor: 'Intel® Core™ i9-12900H 3.80 GHz up to 5.00 GHz, 24MB Cache',
        memory: ' 32GB DDR5 4800MHz Onboard (Not Upgradable)',
        hardDrive: '2TB (1TB x 2) PCIe NVMe SED SSD RAID',
        oldPrice: '$4,999',
        newPrice: '$4,616',
        aboutProduct: "Two tweeters and two woofers equipped with Smart Amp deliver deeper sound with 2.8x higher volume, 3x stronger bass, and up to 3x more dynamic range than conventional speakers. This four-speaker setup delivers surround sound quality optimized by Dolby Atmos algorithms to deliver balanced, multi-dimensional sound across the entire sound spectrum without sacrificing detail clarity.",
        gpu: 'NVIDIA GeForce RTX 3080Ti with 16GB GDDR6 VRAM',
        connection: 'Wi - Fi 6(802.11ax) | Bluetooth 5.0',
        keyBoard: 'Per key RGB steelseries KB',
        weight: '2.4Kg',
        battery: '99.98 Wh 4-cell Li-ion battery'
    },
    {
        id: 27,
        showCaseImgs: [
            "1.png",
            "2.png",
            "3.png",
            "4.png",
            "5.png",
            "6.png",
            "7.png",
            "8.png",
            "9.png",
            "10.png",
        ],
        video: 'src="https://www.youtube.com/embed/loKAnjDvBlU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen',
        productName: 'ROG Zephyrus M16 GU603ZX K8025W',
        brand: 'MSI',
        rate: 5.0,
        reviews: 46,
        sold: 100,
        screen: '16-inch WQXGA (2560 x 1600) 16:10, IPS-level, anti-glare display, 100%, 165Hz, 3ms, 500 nits',
        processor: 'Intel® Core™ i9-12900H Processor 2.5 GHz (24M Cache, up to 5.0 GHz, 14 cores: 6 P-cores and 8 E-cores)',
        memory: ' 32GB DDR5-4800Mhz SO-DIMM (16GB Onboard + 16GB SO-DIMM slot) Upto max 48GB.',
        hardDrive: '2TB M.2 NVMe™ PCIe® 4.0 SSD',
        oldPrice: '$5,199',
        newPrice: '$4,787',
        aboutProduct: "Engineered for extreme durability of up to 20 million keystrokes, the keyboards of the ROG Strix SCAR series are full-size, easy to operate, come with per-key RGB LEDs, perfectly compatible with Aura Sync, providing Ultimate Gaming experience for Gamers.",
        gpu: 'NVIDIA® GeForce RTX™ 3080Ti 8GB GDDR6 + MUX Switch ROG Boost: 1175MHz* at 120W (1125MHz Boost Clock+50MHz OC, 100W+20W Dynamic Boost)',
        connection: 'Wi - Fi 6(802.11ax) | Bluetooth 5.0',
        keyBoard: 'Per key RGB steelseries KB',
        weight: '1.9Kg',
        battery: '90WHrs, 4S1P, 4-cell Li-ion'
    },
    {
        id: 28,
        showCaseImgs: [
            "1.png",
            "2.png",
            "3.png",
            "4.png",
            "5.png",
            "6.png",
        ],
        video: 'src="https://www.youtube.com/embed/IOlleu8hm_M" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen',
        productName: 'Asus ROG Strix SCAR 17 G733ZX LL016W',
        brand: 'ASUS',
        rate: 5.0,
        reviews: 46,
        sold: 100,
        screen: '17.3" WQHD 2K IPS, 165Hz, Wide View, 300nits, Narrow Bezel, Anti-Glare with 72% NTSC, 100% sRGB, 75% Adobe RGB',
        processor: 'Intel® Core™ i9-12900H (3.80 GHz upto 5.00 GHz, 24MB)',
        memory: ' 32GB(16GB*2) DDR5-4800Mhz (2 slots, up to 64GB)',
        hardDrive: '1TB M.2 NVMe™ PCIe® 4.0 SSD',
        oldPrice: '$5,199',
        newPrice: '$4,787',
        aboutProduct: "has dedicated shortcuts for gaming needs in the upper left corner of the keyboard, such as volume up and down, quick Mic off, fan mode switch and quick launch of Armory Crate software. You are also free to customize these hotkeys according to your needs or turn them into micro keys to increase your win rate in the Game.",
        gpu: 'NVIDIA GeForce RTX 3080Ti 16GB GDDR6 Up to 1690MHz Boost Clock, 175W Maximum Graphics Power with Dynamic Boost. Max. 220W CPU-GPU Power with MSI OverBoost Technology',
        connection: 'Wi - Fi 6(802.11ax) | Bluetooth 5.0',
        keyBoard: 'Per-Key RGB',
        weight: '2.7Kg',
        battery: '39.5 x 28.2 x 2.34 ~ 2.83 cm'
    },
    {
        id: 29,
        showCaseImgs: [
            "1.png",
            "2.png",
            "3.png",
            "4.png",
            "5.png",
        ],
        video: 'src="https://www.youtube.com/embed/5kWTsH9Awj0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen',
        productName: 'MSI Stealth GS77 12UH gaming laptop 075VN',
        brand: 'MSI',
        rate: 5.0,
        reviews: 46,
        sold: 100,
        screen: '17.3" QHD (2560x1440) IPS with Anti-Glare, 240Hz, DCI-P3 100% typical',
        processor: 'Intel Core i9-12900H 3.8GHz up to 5.0GHz 24MB',
        memory: ' 32GB (16GBx2) DDR5 4800MHz (2x SO-DIMM socket, up to 64GB SDRAM)',
        hardDrive: '2TB SSD PCIE G4X4 (2 slots)',
        oldPrice: '$5,199',
        newPrice: '$4,787',
        aboutProduct: "Overstroke technology recognizes keystrokes earlier on shorter travel, providing a more responsive experience for intense gaming and work. Activating earlier means faster, easy game entry with greater accuracy.Touchpad larger design",
        gpu: 'NVIDIA GeForce RTX3080 Max-Q 8GB GDDR6, Up to 1345MHz Boost Clock, 105W Maximum Graphics Power with Dynamic Boost.',
        connection: 'Wi - Fi 6(802.11ax) | Bluetooth 5.0',
        keyBoard: 'Per-Key RGB Backlight Keyboard',
        weight: '2.45Kg',
        battery: '4 cells, 99.9Whr'
    },
    {
        id: 30,
        showCaseImgs: [
            "1.png",
            "2.png",
            "3.png",
            "4.png",
            "5.png",

        ],
        video: 'src="https://www.youtube.com/embed/zPqa4JPAyik" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen',
        productName: ' ROG Zephyrus M16 GU603ZW K8021W',
        brand: 'ASUS',
        rate: 5.0,
        reviews: 46,
        sold: 100,
        screen: '16-inch WQXGA (2560 x 1600) 16:10, IPS-level, màn hình chống chói, 100%, 165Hz, 3ms, 500 nits',
        processor: 'Intel® Core™ i9-12900H Processor 2.5 GHz (24M Cache, up to 5.0 GHz, 14 cores: 6 P-cores and 8 E-cores)',
        memory: ' 32GB DDR5-4800Mhz SO-DIMM (16GB Onboard + 16GB SO-DIMM slot) Upto max 48GB ',
        hardDrive: '1TB M.2 NVMe™ PCIe® 4.0 SSD',
        oldPrice: '$5,199',
        newPrice: '$4,787',
        aboutProduct: "Improve comfort in everyday use with the large Touchpad area. More space means more precision with more comfortable hand movements and manipulation during use.",
        gpu: 'NVIDIA® GeForce RTX™ 3070 Ti 8GB GDDR6 + MUX Switch ROG Boost: 1085MHz* at 120W (1035MHz Boost Clock+50MHz OC, 100W+20W Dynamic Boost',
        connection: 'Wi - Fi 6(802.11ax) | Bluetooth 5.0',
        keyBoard: 'Per key RGB steelseries KB',
        weight: '1.9Kg',
        battery: '90WHrs, 4S1P, 4-cell Li-ion'
    },
    {
        id: 31,
        showCaseImgs: [
            "1.png",
            "2.png",
            "3.png",
            "4.png",
            "5.png",
            "6.png",
        ],
        video: 'src="https://www.youtube.com/embed/GHuNxWO0c4I" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen',
        productName: 'MSI GE66 12UGS 405VN',
        brand: 'MSI',
        rate: 5.0,
        reviews: 46,
        sold: 100,
        screen: '15.6" QHD (2560x1440) IPS, 240Hz, 100% sRGB, DCI-P3 100% typical, NanoEdge',
        processor: 'Intel Core i9-12900HK 3.8 GHz up to 5.0 GHz 24MB',
        memory: ' 32GB (16GB x2) DDR5 4800MHz (2 SO-DIMM sockets, up to 64 GB SDRAM) ',
        hardDrive: '1TB SSD PCIE G4X4 (2 slots)',
        oldPrice: '$5,199',
        newPrice: '$4,787',
        aboutProduct: "When you want to customize settings, monitor temperatures, or play around with your Gaming Laptop, Armory Crate is your command center. Real-time monitoring lets you monitor how your GPU, CPU, and memory are doing, and customize the RGB LEDs for each game with Aura Sync. You can also easily change the cooling and fan modes to optimize performance, temperature and noise levels according to your needs. Exclusive Game offers constantly updated will also contribute to enriching your Game library.",
        gpu: 'NVIDIA® GeForce RTX™ 3070Ti 8GB GDDR6 boost clock up to 1585MHz, 150W max graphics power with dynamic boost.',
        connection: 'Wi - Fi 6(802.11ax) | Bluetooth 5.0',
        keyBoard: 'Per key RGB steelseries KB',
        weight: '2.38Kg',
        battery: '4 cells, 99.9Whr'
    },
    {
        id: 32,
        showCaseImgs: [
            "1.png",
            "2.png",
            "3.png",
            "4.png",
            "5.png",
            "6.png",
        ],
        video: 'src="https://www.youtube.com/embed/XHk-mOOibuI&t" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen',
        productName: 'MSI Stealth GS66 12UGS 227VN',
        brand: 'MSI',
        rate: 5.0,
        reviews: 46,
        sold: 100,
        screen: '15.6 inch QHD (2560x1440) IPS with Anti-Glare, 240Hz, DCI-P3 100% typical',
        processor: 'Intel Core i7-12700H 3.6GHz up to 4.9GHz 25MB',
        memory: ' 32GB (16GBx2) DDR5 4800MHz (2x SO-DIMM socket, up to 64GB SDRAM)',
        hardDrive: '1TB SSD PCIE G4X4 (2 slots)',
        oldPrice: '$5,199',
        newPrice: '$4,787',
        aboutProduct: "Equipped with the latest 12th generation CPU  , i9-12900H and RTX 3080 graphics card, MSI Stealth GS77 12UH 075VN possesses a tremendous power with excellent processing and graphics capabilities. Comes with 32GB RAM for smooth multitasking and huge 2TB SSD memory for a comfortable storage space on GS77.",
        gpu: 'NVIDIA GeForce RTX 3070Ti Max-Q 8GB GDDR6, Up to 1300MHz Boost Clock, 105W Maximum Graphics Power with Dynamic Boost.',
        connection: 'Wi - Fi 6(802.11ax) | Bluetooth 5.0',
        keyBoard: 'Per key RGB steelseries KB',
        weight: '2.1Kg',
        battery: '4 cells, 99.9Whr'
    },
    {
        id: 33,
        showCaseImgs: [
            "1.png",
            "2.png",
            "3.png",
            "4.png",
            "5.png",
        ],
        video: 'src="https://www.youtube.com/embed/pZu9ioZFKr0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen',
        productName: 'MSI Stealth GS66 12UGS 227VN',
        brand: 'MSI',
        rate: 5.0,
        reviews: 46,
        sold: 100,
        screen: '15.6 inch QHD (2560x1440) IPS with Anti-Glare, 240Hz, DCI-P3 100% typical',
        processor: 'Intel Core i7-12700H 3.6GHz up to 4.9GHz 25MB',
        memory: ' 32GB (16GBx2) DDR5 4800MHz (2x SO-DIMM socket, up to 64GB SDRAM) ',
        hardDrive: '1TB SSD PCIE G4X4 (2 slots)',
        oldPrice: '$5,199',
        newPrice: '$4,787',
        aboutProduct: "Owning a 17.3-inch QHD screen with extremely terrible parameters for gaming ability that is up to 240Hz refresh rate and 100% sRGB color standard, MSI Stealth GS77 12UH 075VN will be a great helper for you in the communication phase. Compete in FPS games that help you win and at work.",
        gpu: '	NVIDIA GeForce RTX 3070Ti Max-Q 8GB GDDR6, Up to 1300MHz Boost Clock, 105W Maximum Graphics Power with Dynamic Boost.',
        connection: 'Wi - Fi 6(802.11ax) | Bluetooth 5.0',
        keyBoard: 'Per key RGB steelseries KB',
        weight: '2.1Kg',
        battery: '4 cells, 99.9Whr'
    },
    {
        id: 34,
        showCaseImgs: [
            "1.png",
            "2.png",
            "3.png",
            "4.png",
            "5.png",
            "6.png",
        ],
        video: 'src="https://www.youtube.com/embed/y_4AEKiUCRI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen',
        productName: 'ASUS ROG Zephyrus G14 GA402RJ L8030W',
        brand: 'MSI',
        rate: 5.0,
        reviews: 46,
        sold: 100,
        screen: '14" WQXGA (2560 x 1600) 16:10, IPS, 120Hz, 3ms, DCI-P3: 100%, Pantone Validated, anti-glare display, 500nits, Adaptive-Sync, Dolby vision',
        processor: 'AMD Ryzen™ 7 6800HS 3.2GHz up to 4.7GHz 16MB',
        memory: ' 16GB (8GB Onboard + 8GB) DDR5 4800MHz (1x SO-DIMM socket, up to 24GB SDRAM) ',
        hardDrive: '1TB M.2 NVMe™ PCIe® 4.0 SSD (1 slot)',
        oldPrice: '$5,199',
        newPrice: '$4,787',
        aboutProduct: "Optimized for gaming is MSI's exclusive Cooler Boost cooling system - Cooler Boost Trinity+. With the world's thinnest 0.1 mm propeller with 3 blades and 7 ducts, the new Cooler Boost Trinity+ heatsink enhances airflow, delivering the best gaming experience on the GS66 Stealth.",
        gpu: 'AMD Radeon™ RX 6700S 8GB GDDR6 With ROG Boost: up to 100W (SmartShift)',
        connection: 'Wi - Fi 6(802.11ax) | Bluetooth 5.0',
        keyBoard: 'Per key RGB steelseries KB',
        weight: '1.6Kg',
        battery: '4 cells, 99.9Whr'
    },
    {
        id: 35,
        showCaseImgs: [
            "1.png",
            "2.png",
            "3.png",
            "4.png",
            "5.png",
        ],
        video: 'src="https://www.youtube.com/embed/u0ZogiVtYvE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen',
        productName: 'Asus ROG Flow Z13 GZ301ZC LD110W',
        brand: 'ASUS',
        rate: 5.0,
        reviews: 46,
        sold: 100,
        screen: '13.4-inch WUXGA (1920 x 1200) 16:10 aspect ratio, 120Hz, IPS-level, glossy display, Touch Screen, 100% sRGB, Adaptive-Sync, Pantone Validated, Pen support, MUX Switch + Optimus',
        processor: 'Intel Core i7-12700H (2.3 GHz up to 4.7 GHz, 24M Cache)',
        memory: ' 16GB (8GBx2) LPDDR5 onboard dual channel memory ',
        hardDrive: '512GB M.2 2230 NVMe™ PCIe 4.0 SSD',
        oldPrice: '$5,199',
        newPrice: '$4,787',
        aboutProduct: "Thanks to the latest DDR5-4800 standard RAM, MSI Stealth GS77 12UH 075VN helps you experience better speed and responsiveness, taking your gaming experience to the next level by maximizing performance. .",
        gpu: 'NVIDIA®GeForce RTX™ 3050 4GB GDDR6, ROG Boost: 1107.5MHz* at 40W (1057.5MHz Boost Clock+50MHz OC, 35W+5W Dynamic Boost)',
        connection: 'Wi - Fi 6(802.11ax) | Bluetooth 5.0',
        keyBoard: 'Per key RGB steelseries KB',
        weight: '1.18Kg',
        battery: '56WHrs, 4S1P, 4-cell Li-ion'
    },
    {
        id: 36,
        showCaseImgs: [
            "1.png",
            "2.png",
            "3.png",
            "4.png",
            "5.png",
            "6.png",
        ],
        video: 'src="https://www.youtube.com/embed/VzrR9-upMCA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen',
        productName: 'ASUS TUF A15 FA507RR HN835W',
        brand: 'MSI',
        rate: 5.0,
        reviews: 46,
        sold: 100,
        screen: '15.6" FHD (1920 x 1080) IPS, 144Hz, Wide View, 250nits, Narrow Bezel, Non-Glare with 45% NTSC, 63% sRGB',
        processor: 'AMD Ryzen 7 6800H 3.2GHz up to 4.7GHz 20MB',
        memory: ' 16GB DDR5 4800MHz (2x SO-DIMM socket, up to 32GB SDRAM) ',
        hardDrive: '512GB M.2 NVMe™ PCIe® 3.0 SSD (1 slot M.2 PCIE SSD is available)',
        oldPrice: '$5,199',
        newPrice: '$4,787',
        aboutProduct: "The Thunderbolt 4 port on the MSI Stealth GS77 12UH 075VN enhances your usage experience with USB standard support for super-high data transfer speeds, PD charging, and connecting to multiple devices at the same time. With up to 3 times higher output charging power and up to 100 Watt input charging, more convenient for daily use.",
        gpu: 'NVIDIA GeForce RTX 3070 8GB GDDR6, Up to 1460MHz* at 140W (1410MHz Boost Clock+50MHz OC, 115W+25W Dynamic Boost)',
        connection: 'Wi - Fi 6(802.11ax) | Bluetooth 5.0',
        keyBoard: 'Per key RGB steelseries KB',
        weight: '2.2Kg',
        battery: '4 Cells 56WHr'
    },
    
];